dab init --database-type "mssql" --connection-string "@env('DATABASE_CONNECTION_STRING')"

dab add "Customer" --source "SalesLT.Customer" --permissions "anonymous:*"
dab add "ProductModel" --source "SalesLT.ProductModel" --permissions "anonymous:*"
dab add "ProductDescription" --source "SalesLT.ProductDescription" --permissions "anonymous:*"
dab add "Product" --source "SalesLT.Product" --permissions "anonymous:*"
dab add "ProductModelProductDescription" --source "SalesLT.ProductModelProductDescription" --permissions "anonymous:*"
dab add "ProductCategory" --source "SalesLT.ProductCategory" --permissions "anonymous:*"
dab add "Address" --source "SalesLT.Address" --permissions "anonymous:*"
dab add "CustomerAddress" --source "SalesLT.CustomerAddress" --permissions "anonymous:*"
dab add "SalesOrderDetail" --source "SalesLT.SalesOrderDetail" --permissions "anonymous:*"
dab add "SalesOrderHeader" --source "SalesLT.SalesOrderHeader" --permissions "anonymous:*"

dab update Address --relationship customerAddresses --target.entity CustomerAddress --cardinality many --relationship.fields "AddressID:AddressID"
dab update Customer --relationship customerAddresses --target.entity CustomerAddress --cardinality many --relationship.fields "CustomerID:CustomerID"
dab update ProductCategory --relationship products --target.entity Product --cardinality many --relationship.fields "ProductCategoryID:ProductCategoryID"
dab update ProductModel --relationship products --target.entity Product --cardinality many --relationship.fields "ProductModelID:ProductModelID"
dab update ProductCategory --relationship productCategories --target.entity ProductCategory --cardinality many --relationship.fields "ProductCategoryID:ParentProductCategoryID"
dab update ProductDescription --relationship productModelProductDescriptions --target.entity ProductModelProductDescription --cardinality many --relationship.fields "ProductDescriptionID:ProductDescriptionID"
dab update ProductModel --relationship productModelProductDescriptions --target.entity ProductModelProductDescription --cardinality many --relationship.fields "ProductModelID:ProductModelID"
dab update Product --relationship salesOrderDetails --target.entity SalesOrderDetail --cardinality many --relationship.fields "ProductID:ProductID"
dab update SalesOrderHeader --relationship salesOrderDetails --target.entity SalesOrderDetail --cardinality many --relationship.fields "SalesOrderID:SalesOrderID"
dab update Address --relationship salesOrderHeaders --target.entity SalesOrderHeader --cardinality many --relationship.fields "AddressID:BillToAddressID"
dab update Address --relationship salesOrderHeaders --target.entity SalesOrderHeader --cardinality many --relationship.fields "AddressID:ShipToAddressID"
dab update Customer --relationship salesOrderHeaders --target.entity SalesOrderHeader --cardinality many --relationship.fields "CustomerID:CustomerID"